version: 2.1
orbs: 
  salesforce-sfdx: circleci/salesforce-sfdx@2.2.0
  jobs:
  create-open-delete:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: mngc98@gmail.com
      - sfdx/scratch-create:
          scratch-alias: circleci
          scratch-config: ./config/project-scratch-def.json
      - sfdx/scratch-open:
          scratch-alias: circleci
      - sfdx/scratch-delete:
          scratch-alias: circleci
orbs:
  sfdx: circleci/salesforce-sfdx@x.y
version: 2.1
workflows:
  basic-test:
    jobs:
      - create-open-delete

jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: mngc98@gmail.com
      - run:
          command: >
            echo You now have access to the sfdx cli and may execute commands
            against it.

            sfdx auth:list
          name: Run your SFDX commands here
orbs:
  sfdx: circleci/salesforce-sfdx@x.y
version: 2.1
workflows:
  basic-test:
    jobs:
      - install_authenticate